/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omnividea_media_codec_audio_JavaDecoder */

#ifndef _Included_com_omnividea_media_codec_audio_JavaDecoder
#define _Included_com_omnividea_media_codec_audio_JavaDecoder
#ifdef __cplusplus
extern "C" {
#endif
#undef com_omnividea_media_codec_audio_JavaDecoder_DEBUG
#define com_omnividea_media_codec_audio_JavaDecoder_DEBUG 0L
/* Inaccessible static: jdkInit */
/* Inaccessible static: forName3ArgsM */
/* Inaccessible static: getSystemClassLoaderM */
/* Inaccessible static: systemClassLoader */
/* Inaccessible static: getContextClassLoaderM */
/* Inaccessible static: class_00024java_00024lang_00024String */
/* Inaccessible static: class_00024java_00024lang_00024ClassLoader */
/* Inaccessible static: class_00024java_00024lang_00024Class */
/* Inaccessible static: class_00024java_00024lang_00024Thread */
#undef com_omnividea_media_codec_audio_JavaDecoder_DEBUG
#define com_omnividea_media_codec_audio_JavaDecoder_DEBUG 1L
#undef com_omnividea_media_codec_audio_JavaDecoder_DEBUG
#define com_omnividea_media_codec_audio_JavaDecoder_DEBUG 0L
/* Inaccessible static: bigEndian */
/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    isBigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_isBigEndian
  (JNIEnv *, jclass);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_init
  (JNIEnv *, jobject);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    open_codec
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_open_1codec
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    close_codec
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_close_1codec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    init_decoding
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_init_1decoding
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    convert
 * Signature: (ILjava/lang/Object;JILjava/lang/Object;JJD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_convert
  (JNIEnv *, jobject, jlong, jobject, jlong, jint, jobject, jlong, jlong, jdouble);

/*
 * Class:     com_omnividea_media_codec_audio_JavaDecoder
 * Method:    lastAudioSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_omnividea_media_codec_audio_JavaDecoder_lastAudioSize
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
