/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_omnividea_media_parser_video_Parser */

#ifndef _Included_com_omnividea_media_parser_video_Parser
#define _Included_com_omnividea_media_parser_video_Parser
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: lastAudioTime */
/* Inaccessible static: lastVideoTime */
/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_omnividea_media_parser_video_Parser_avInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avOpen
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avOpen
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avClose
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avClose
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avIsVideoPresent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avIsVideoPresent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetWidth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_omnividea_media_parser_video_Parser_avGetWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetHeight
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_omnividea_media_parser_video_Parser_avGetHeight
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetFrameRate
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_omnividea_media_parser_video_Parser_avGetFrameRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetBitRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetBitRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetDurationSec
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetDurationSec
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avIsSeekable
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avIsSeekable
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetNextFrameTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetNextFrameTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avIsAudioPresent
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avIsAudioPresent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetAudioBitRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetAudioBitRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetAudioSampleRate
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetAudioSampleRate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetAudioChannelNumber
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_omnividea_media_parser_video_Parser_avGetAudioChannelNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avSetPosition
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avSetPosition
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avProcess
 * Signature: (ILjava/lang/Object;JJZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avProcess
  (JNIEnv *, jobject, jlong, jobject, jlong, jlong, jboolean, jint);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avProcessAudio
 * Signature: (ILjava/lang/Object;JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avProcessAudio
  (JNIEnv *, jobject, jlong, jobject, jlong, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetAudioSampleSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_omnividea_media_parser_video_Parser_avGetAudioSampleSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetAudioSampleTimestamp
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetAudioSampleTimestamp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetFirstVideoTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetFirstVideoTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avGetFirstAudioTime
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_omnividea_media_parser_video_Parser_avGetFirstAudioTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_omnividea_media_parser_video_Parser
 * Method:    avIsBigEndian
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_omnividea_media_parser_video_Parser_avIsBigEndian
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
